apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvoice
  namespace: karatly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvoice
  template:
    metadata:
      labels:
        app: openvoice
    spec:
      containers:
        - name: openvoice
          image: karatly-openvoice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
